const express = require("express");
const router = express.Router();

const authRoutes = require("./auth");
const videocallRoutes = require("./videocall");
const otpRoutes = require("./otp");
const superadminRoutes = require("./superadmin");
const settingsRoutes = require("./settings");
const reportsRoutes = require("./reports");
const logsRoutes = require("./logs");
const adminRoutes = require("./admins");
const adminUsersRoutes = require("./adminUsers");
const adminDashboardRoutes = require("./adminRoutes");
const adminMessagesRoutes = require("./messages");
const doctorRoutes = require("./doctor");
const doctorVideoRoutes = require("./doctorVideo");
const doctorPatientsRoutes = require("./doctorPatients");
const clinicalEncounterRoutes = require("./clinicalEncounter");
const appointmentApiRoutes = require("./appointmentApi");
const scheduleRoutes = require("./scheduleRoutes");
const patientRoutes = require("./patientRoutes");
const patientDoctorsRoutes = require("./patientDoctors");
const notificationsRoutes = require("./notifications");
const chatbotRoutes = require("./chatbot.routes");
const internalRoutes = require("./internal");
const subscriptionRoutes = require("./subscription");
const adminSubscriptionRoutes = require("./adminSubscription");
const pharmacyRoutes = require("./pharmacy");
const supportRoutes = require("./support");
const userRoutes = require("./user");

router.use("/auth", authRoutes);
router.use("/videocall", videocallRoutes);
router.use("/otp", otpRoutes);
router.use("/superadmin", superadminRoutes);
router.use("/superadmin/settings", settingsRoutes);
router.use("/settings", settingsRoutes);
router.use("/superadmin/reports", reportsRoutes);
router.use("/superadmin/logs", logsRoutes);
router.use("/superadmin/activity-logs", logsRoutes);
router.use("/admins", adminRoutes);
router.use("/admin/users", adminUsersRoutes);
router.use("/admin", adminDashboardRoutes);
router.use("/admin/messages", adminMessagesRoutes);
router.use("/doctor", doctorPatientsRoutes);
router.use("/doctor", doctorRoutes);
router.use("/doctor/video", doctorVideoRoutes);
router.use("/clinical-encounter", clinicalEncounterRoutes);
router.use("/appointments", appointmentApiRoutes);
router.use("/schedule", scheduleRoutes);
router.use("/patient", patientDoctorsRoutes);
router.use("/patient", patientRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/chatbot", chatbotRoutes);
router.use("/internal", internalRoutes);
router.use("/subscription", subscriptionRoutes);
router.use("/subscribers", subscriptionRoutes);
router.use("/admin/subscription-management", adminSubscriptionRoutes);
router.use("/pharmacy", pharmacyRoutes);
router.use("/support", supportRoutes);
router.use("/user", userRoutes);
router.use("/users", userRoutes);

module.exports = router;
